### ISSUE TITLE
Images break everything

### ISSUE THREAD

**Issue by s1ddok** [t-ae/tensorboardx-s4tf#2]
Hi! Thanks for you wonderful project!

I'm using it and it seems to work fine, but logging images not only doesn't work for me, but also breaks other streams and tensorboard show me nothing. Are you aware of any way to debug such things? Tensorboard doesn't provide any logs in developer console. Code that break everything:

```
writer.addImages(tag: "images",
                 images: tensorImage / 2.0 + 0.5,
                 globalStep: epoch)
```

**Comment by t-ae** [comment]
I've never got such problem & I don't know how to debug it.

Can you try `TestPlot` target?
https://github.com/t-ae/tensorboardx-s4tf/blob/master/README.md#requirements

```
$ swift run TestPlot
$ tensorboard --logdir /tmp/tensorboardx
```

It's working correctly in my environment:

```
numpy==1.16.4
Pillow==7.0.0
tensorboard==2.1.1
tensorboardX==2.0
```

**Comment by s1ddok** [comment]
Okay I've tracked down the problem. You can't call this method multiple time with the same globalStep name + you have to call flush in order for it to work properly
